name: Projectile Motion with Air Resistance

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Python version

    - name: Install dependencies
      
      run:
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  
    - name: Install linter
      run:
        pip install pylint
    - name: List directory contents
      run: ls -al
    - name: lint projectile_unit_test.py
      run: pylint projectile_unit_test.py > pylint_projectile_output.log

    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: pylint_output
        path: pylint_output.log

    
